parameters:
- name: environment
  type: string

- name: versionName
  type: string

jobs:
- job: Deployment
  environment: ${{ parameters.environment }} # points to environments in Azure DevOps  
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux:
        BUILD: deploy
  steps:
  - script: |
      echo deploying ${{ parameters.versionName }}
