jobs:
# - template: ./.azure/azure-nightly-template-osx.yml
#   parameters:
#     name: macOS
#     vmImage: macOS-latest
#     os: osx

- template: ./.azure/azure-nightly-template-linux.yml
  parameters:
    name: Linux
    vmImage: ubuntu-latest
    os: linux

# - template: ./.azure/azure-nightly-template-windows.yml
#   parameters:
#    name: Windows
#    vmImage: windows-latest
#    os: windows
