parameters:
- name: environment
  type: string

- name: releaseTag
  type: string

jobs:
- deployment: Deploy
  environment: ${{ parameters.environment }} # points to environments in Azure DevOps  
  pool:
    vmImage: ubuntu-latest
  strategy:
    runOnce:
      deploy:
        steps:
        - script: |
            echo deploying ${{ parameters.releaseTag }}
