jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
    maxParallel: 1
  steps:
  - script: |
      brew install gnu-tar
      tar --help
      tar --version
    displayName: 'Test'
