jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
    maxParallel: 1
  steps:
  - bash: |
      tar --help
      tar --version
      ls /dev/
      ls /dev/null
      tar --force-local -cvf $HOME/jackal.tar -T /dev/null
      tar --force-local -tvf $HOME/jackal.tar
      ls -lh 
      echo "Going to execute script"
      source ./tar.sh
    displayName: Test in Bash
  - powershell: |
      tar --force-local -cvf $HOME/jackal.tar -T /dev/null
      tar --force-local -tvf $HOME/jackal.tar
      tar --help
      tar --version
      tar --force-local -cvf $HOME/jackal.tar -T /dev/null
      tar --force-local -tvf $HOME/jackal.tar
      echo "Going to execute script"
      source ./tar.sh
    displayName: Test in Powershell
