jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
    maxParallel: 1
  variables:
    CACHE_ROOT: "$(Build.SourcesDirectory)/.stack-root"
    CACHE_WORK: "$(Build.SourcesDirectory)/.stack-work"
    CACHE_PROGAMS: $(ls / 2> /dev/null)
  steps:
  - script: |
      echo "Going to execute script"
      echo $(CACHE_ROOT)
      echo $(CACHE_WORK)
      echo $(CACHE_PROGAMS)
      source ./tar.sh
    displayName: 'Installation ${{parameters.os}}'
