jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
      stack-lts:
        BUILD: stack
    maxParallel: 1
  steps:
  - script: |
      printenv
      tar --help
      tar --version
      ls /dev/
      ls /dev/null
      echo "Going to execute script"
      source ./tar.sh
    displayName: 'Installation ${{parameters.os}}'
